protected/models/Session.php
<?php

Yii::import('application.models._base.BaseSession');

class Session extends BaseSession
{
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
}

protected/controllers/FilmController.php
<?php

class FilmController extends GxController {


	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Film'),
		));
	}

	public function actionCreate() {
		$model = new Film;


		if (isset($_POST['Film'])) {
			$model->setAttributes($_POST['Film']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Film');


		if (isset($_POST['Film'])) {
			$model->setAttributes($_POST['Film']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Film')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Film');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Film('search');
		$model->unsetAttributes();

		if (isset($_GET['Film']))
			$model->setAttributes($_GET['Film']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

protected/controllers/SessionController.php
<?php

class SessionController extends GxController {


	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Session'),
		));
	}

	public function actionCreate() {
		$model = new Session;


		if (isset($_POST['Session'])) {
			$model->setAttributes($_POST['Session']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Session');


		if (isset($_POST['Session'])) {
			$model->setAttributes($_POST['Session']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Session')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Session');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Session('search');
		$model->unsetAttributes();

		if (isset($_GET['Session']))
			$model->setAttributes($_GET['Session']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

protected/controllers/TicketController.php
<?php

class TicketController extends GxController {


	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Ticket'),
		));
	}

	public function actionCreate() {
		$model = new Ticket;


		if (isset($_POST['Ticket'])) {
			$model->setAttributes($_POST['Ticket']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Ticket');


		if (isset($_POST['Ticket'])) {
			$model->setAttributes($_POST['Ticket']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Ticket')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Ticket');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Ticket('search');
		$model->unsetAttributes();

		if (isset($_GET['Ticket']))
			$model->setAttributes($_GET['Ticket']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

protected/views/session/_form.php
<div class="form">


<?php $form = $this->beginWidget('GxActiveForm', array(
	'id' => 'session-form',
	'enableAjaxValidation' => false,
));
?>

	<p class="note">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

    <?php Yii::import('application.extensions.CJuiDateTimePicker.CJuiDateTimePicker');
        $this->widget('CJuiDateTimePicker',array(
            'model'=>$model, //Model object
            'attribute'=>'time', //attribute name
            'mode'=>'datetime', //use "time","date" or "datetime" (default)
            'options'=>array(
                "dateFormat"=>'yy-mm-dd',
                //'showSecond'=>true,
            )
        ));
    ?>

		<div class="row">
		<?php echo $form->labelEx($model,'time'); ?>
		<?php //echo $form->textField($model, 'time'); ?>
		<?php echo $form->error($model,'time'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'cinema_hal_id'); ?>
		<?php echo $form->dropDownList($model, 'cinema_hal_id', GxHtml::listDataEx(CinemaHal::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'cinema_hal_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'film_id'); ?>
		<?php echo $form->dropDownList($model, 'film_id', GxHtml::listDataEx(Film::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'film_id'); ?>
		</div><!-- row -->

		<label><?php echo GxHtml::encode($model->getRelationLabel('tickets')); ?></label>
		<?php echo $form->checkBoxList($model, 'tickets', GxHtml::encodeEx(GxHtml::listDataEx(Ticket::model()->findAllAttributes(null, true)), false, true)); ?>

<?php
echo GxHtml::submitButton(Yii::t('app', 'Save'));
$this->endWidget();
?>
</div><!-- form -->

protected/views/session/_search.php
<div class="wide form">

<?php $form = $this->beginWidget('GxActiveForm', array(
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model, 'id'); ?>
		<?php echo $form->textField($model, 'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'time'); ?>
		<?php echo $form->textField($model, 'time'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'cinema_hal_id'); ?>
		<?php echo $form->dropDownList($model, 'cinema_hal_id', GxHtml::listDataEx(CinemaHal::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model, 'film_id'); ?>
		<?php echo $form->dropDownList($model, 'film_id', GxHtml::listDataEx(Film::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>

	<div class="row buttons">
		<?php echo GxHtml::submitButton(Yii::t('app', 'Search')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/session/_view.php
<div class="view">

	<?php echo GxHtml::encode($data->getAttributeLabel('id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->id), array('view', 'id' => $data->id)); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('time')); ?>:
	<?php echo GxHtml::encode($data->time); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('cinema_hal_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->cinemaHal)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('film_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->film)); ?>
	<br />

</div>

protected/views/session/admin.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Manage'),
);

$this->menu = array(
		array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
		array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('session-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1><?php echo Yii::t('app', 'Manage') . ' ' . GxHtml::encode($model->label(2)); ?></h1>

<p>
You may optionally enter a comparison operator (&lt;, &lt;=, &gt;, &gt;=, &lt;&gt; or =) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo GxHtml::link(Yii::t('app', 'Advanced Search'), '#', array('class' => 'search-button')); ?>
<div class="search-form">
<?php $this->renderPartial('_search', array(
	'model' => $model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id' => 'session-grid',
	'dataProvider' => $model->search(),
	'filter' => $model,
	'columns' => array(
		'id',
		'time',
        array(
            'name'=>'cinemaHal.cinema_id',
            'header'=>'cinema_id'
        ),
        array(
            'name'=>'cinemaHal.number',
            'header'=>'number'
        ),
		array(
				'name'=>'cinema_hal_id',
				'value'=>'GxHtml::valueEx($data->cinemaHal)',
				'filter'=>GxHtml::listDataEx(CinemaHal::model()->findAllAttributes(null, true)),
				),
		array(
				'name'=>'film_id',
				'value'=>'GxHtml::valueEx($data->film)',
				'filter'=>GxHtml::listDataEx(Film::model()->findAllAttributes(null, true)),
				),
		array(
			'class' => 'CButtonColumn',
		),
	),
)); ?>

protected/views/session/create.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Create'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url' => array('index')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url' => array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'Create') . ' ' . GxHtml::encode($model->label()); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model,
		'buttons' => 'create'));
?>

protected/views/session/index.php
<?php

$this->breadcrumbs = array(
	Session::label(2),
	Yii::t('app', 'Index'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'Create') . ' ' . Session::label(), 'url' => array('create')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . Session::label(2), 'url' => array('admin')),
);
?>

<h1><?php echo GxHtml::encode(Session::label(2)); ?></h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); 

protected/views/session/update.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model) => array('view', 'id' => GxActiveRecord::extractPkValue($model, true)),
	Yii::t('app', 'Update'),
);

$this->menu = array(
	array('label' => Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label' => Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label' => Yii::t('app', 'View') . ' ' . $model->label(), 'url'=>array('view', 'id' => GxActiveRecord::extractPkValue($model, true))),
	array('label' => Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'Update') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model));
?>

protected/views/session/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->id)),
	array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data' => $model,
	'attributes' => array(
'id',
'time',
array(
			'name' => 'cinemaHal',
			'type' => 'raw',
			'value' => $model->cinemaHal !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->cinemaHal)), array('cinemaHal/view', 'id' => GxActiveRecord::extractPkValue($model->cinemaHal, true))) : null,
			),
array(
			'name' => 'film',
			'type' => 'raw',
			'value' => $model->film !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->film)), array('film/view', 'id' => GxActiveRecord::extractPkValue($model->film, true))) : null,
			),
	),
)); ?>

<h2><?php echo GxHtml::encode($model->getRelationLabel('tickets')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->tickets as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('ticket/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?>